Repository chef/ohai, pull requests merged in 2018-07, with the labels that each got.

#1208 Resolve several performance issues identified by Rubocop
  .rubocop.yml
  lib/ohai/plugins/linux/network.rb
Labels: Version: Bump Minor

#1220 Prep 13.10 release
  RELEASE_NOTES.md
Labels: Version: Bump Minor

#1219 Bump version to 14.3 + add release notes
  RELEASE_NOTES.md
  VERSION
  lib/ohai/version.rb
Labels: Expeditor: Skip Version Bump

#1222 Actually bump to 13.10
  VERSION
  lib/ohai/version.rb
Labels: Expeditor: Skip Version Bump

#1210 Add system_enclosure plugin for Windows
  lib/ohai/plugins/windows/system_enclosure.rb
  spec/unit/plugins/windows/system_enclosure_spec.rb
Labels: Status: Ready for Merge

#1223 Update Expeditor to clean branches / bump minors
  .expeditor/config.yml
Labels: Status: Pending Contributor Response
